# Generated by Django 5.1.4 on 2025-02-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectwallet', '0002_connectwallet_created_at_connectwallet_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectwallet',
            options={'verbose_name': 'Connected Wallet', 'verbose_name_plural': 'Connected Wallets'},
        ),
        migrations.AlterModelOptions(
            name='walletasset',
            options={'verbose_name': 'Wallet Asset', 'verbose_name_plural': 'Wallet Assets'},
        ),
    ]
