# Generated by Django 5.1.4 on 2025-02-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='govt_issued_id',
            field=models.ImageField(blank=True, null=True, upload_to='govt_issued_ids/'),
        ),
    ]
