# Generated by Django 5.1.4 on 2025-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',  # Change this to 'investmentplan'
            name='required_deposit',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
            preserve_default=False,
        ),
    ]
