# Generated by Django 5.1.4 on 2025-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_investment_required_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='required_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
