# Generated by Django 5.1.4 on 2025-01-20 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_alter_investmentplan_required_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentplan',
            old_name='duration_months',
            new_name='duration_days',
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='required_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
