# Generated by Django 5.1.4 on 2025-02-05 10:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_rename_duration_months_investmentplan_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='required_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
